# Generated by Django 5.0 on 2024-03-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='resturant_main_image')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sum_of_rates', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('number_of_rates', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reservation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ResturantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resturants')),
            ],
        ),
        migrations.CreateModel(
            name='ResturantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.SmallIntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResturantReservationIdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resturant_reservation_id_image')),
            ],
        ),
        migrations.CreateModel(
            name='ResturantComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('resturant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resturant.resturant')),
            ],
        ),
    ]
